### ISSUE TITLE
Support Backpack v6

### ISSUE THREAD

**Issue by k-iuretig-alfonsino** [thomascombe/backpack-async-export#15]
Any chance to update this package for Backpack 6?

Thanks in advance!

**Comment by thomascombe** [comment]
Hi,
I current don’t have any project with backpack 6 for now.

But yes I think I have to update this package in the next weeks.

**Comment by rodrigofcaba** [comment]
Hi, it would be much appreciated! The package is really good but I have already Backpack v6 in my app.

Thanks in advance!

**Comment by thomascombe** [comment]
Hi, it's available on 2.1.0 tag 👍
